name: Build LaTeX PDF and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Only triggers on pushes to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install TeX Live
      run: sudo apt-get update && sudo apt-get install -y texlive-full

    - name: Compile PDF using Makefile
      run: make

    - name: Move PDF to docs directory
      run: |
        mkdir -p docs
        mv *.pdf docs/  # Assumes your PDF is in the root directory after "make"

    - name: Commit and Push to Main
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add docs/*.pdf
        git commit -m "Update PDF on push to main"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
